### ISSUE TITLE
Add support for decimals

### ISSUE THREAD

**Issue by aBooDyy** [aBooDyy/Progress-Expansion#10]
Maximum value should have support for decimals but actually doesn't, so I have to fix that.
Issue reported by TechLead#4312 in Discord.

**Comment by Albert481** [comment]
Console getting spammed with the following:

[Progress] Couldn't get the number from Loading.... The progress will be 0%.


Using Math, Levelpoints for this.
"  &8[%progress_bar_{LevelPoints_exp_amount}_m:{math_{LevelPoints_exp_required}[precision:0]}%&8]"

**Comment by aBooDyy** [comment]
The placeholder is incorrect.
Use this:
```
%progress_bar_{LevelPoints_exp_amount}_m:{math_$(LevelPoints_exp_required)$+0[precision:0]}%
```

**Comment by Albert481** [comment]
Console still getting spammed even after using the above.

 [Progress] Couldn't get the number from Loading...m:{mathLoading...[precision:0]}. The progress will be 0%.

**Comment by aBooDyy** [comment]
Hello @Albert481,

I have just [updated the expansion](https://api.extendedclip.com/expansions/progress/versions/progress-21/). The new version has support for decimals in the maximum value field so now it should work without using Math expansion.

To update the expansion, re-download it:
> /papi ecloud download Progress
> /papi reload

Let me know if the issue still occurs.

Regards,
aBooDyy

**Comment by Albert481** [comment]
Still getting: [Progress] Couldn't get the number from Loading.... The progress will be 0%.

Don't know what's the cause. It gets spammed too fast, maybe 10 of that ^ in 1 sec.

**Comment by aBooDyy** [comment]
> Still getting: [Progress] Couldn't get the number from Loading.... The progress will be 0%.
> 
> 
> 
> Don't know what's the cause. It gets spammed too fast, maybe 10 of that ^ in 1 sec.

Hello there,

Would you please share the placeholder you're using?
With the new version (v2.1) you don't need to use Math placeholder inside progress placeholder.

About the spamming messages, it is most likely because you're parsing the placeholder too many times through a scoreboard or somewhere else.

To make sure you have the latest version, execute the following command:
> /papi info progress

To download the latest version:
> /papi ecloud refresh
> /papi ecloud download progress 
> /papi reload

Let me know how it goes.

Regards,
aBooDyy
