### ISSUE TITLE
Placeholder in placeholder

### ISSUE THREAD

**Issue by martijnpu** [aBooDyy/Progress-Expansion#2]
Hi,

I've created the following placeholder. It should display the server RAM usage in percentage. I use for the parameter the following placeholder. `math_{server_ram_used}/{server_ram_total}*50[precision:0]`. I've got this from [https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/).
`%progress_bar_{math_{server_ram_used}/{server_ram_total}*50[precision:0]}_c:&a|_p:&e|_r:&7|_l:50_m:50_fullbar:&cServer is overheating!%`

Unfortunately it displays nothing, but when I use another placeholder without placeholders in the math function. I know the math placeholder in its own is valid. When I use the following it displays a corrent progress bar. Here I don't use placeholders in the matn placeholder.
`%progress_bar_{math_2/5*50[precision:0]}_c:&a|_p:&e|_r:&7|_l:50_m:50_fullbar:&cServer is overheating!%`

Can you help me solve this?

martijnpu

**Comment by aBooDyy** [comment]
Hello,
That happens because it parse the placeholders whenever it reaches an open curly braces `{`, and a closing curly braces `}` which this first placeholder `{math_{server_ram_used}` and by this, it will mess up the whole placeholders in there.

I would add support for another pair of opening and closing symbol to support such a placeholders. Will work on it soon.

**Comment by aBooDyy** [comment]
Just updated the expansion and added the support to use a placeholder in a placeholder inside of progress placeholder using `$(placeholder)$`.
So the placeholder would be now 
`%progress_bar_$(math_{server_ram_used}/{server_ram_total}*50[precision:0])$_c:&a|_p:&e|_r:&7|_l:50_m:50_fullbar:&cServer is overheating!%`

To download the latest version, run the following commands:
```
/papi ecloud refresh
/papi ecloud download Progress
/papi reload
```

Thanks for reporting that.
