### ISSUE TITLE
Progess Bar (With MMocore)

### ISSUE THREAD

**Issue by Buxarov** [aBooDyy/Progress-Expansion#4]
When used:% progress_bar_ {mmocore_profession_percent_mining}% does not return any message, but only when numbers end in decimals (57.8%), but when player is 58%, it shows progress bar correctly

Regards !

**Comment by aBooDyy** [comment]
Hello,

Thanks for reporting,
The issue has been fixed (23fd03e) and the update has been pushed to the [eCloud](https://api.extendedclip.com/expansions/progress/).

You can update the expansion by simply redownloading it:
> /papi ecloud download Progress
> /papi reload

Thanks for using my Progress Expansion,
aBooDyy

**Comment by Buxarov** [comment]
Hi,

I just installed the new expansion and the problem continues, only now a message appears in the console, I attach some screenshots

![Progress2](https://user-images.githubusercontent.com/35592260/78463392-693bbb80-76b2-11ea-8f62-ac7c239a2d63.png)
![Progress3](https://user-images.githubusercontent.com/35592260/78463394-69d45200-76b2-11ea-87c3-9183df168081.png)
![Progress1](https://user-images.githubusercontent.com/35592260/78463395-6a6ce880-76b2-11ea-9a44-7fc1daf7defc.png)

Placeholder:
%progress_bar_{mmocore_profession_percent_mining}_m:100%

**Comment by aBooDyy** [comment]
Oh, I see. `96,5` isn't actually a decimal number due to the comma  `,`. It should be dot `.` instead.
This can be fixed with a JavaScript placeholder but I'll just add support for it in my expansion.

**Comment by aBooDyy** [comment]
Hello again,
I've implemented a new option for the users to replace characters in the placeholder field with whatever they want.

So in your case, you would want to replace the comma `,` with a dot `.`.
To do this, the new `replace_placeholder` option would be like the following in your PlaceholderAPI config:
```yml
  progress:
    replace_placeholder:
    - ',;.'
```

Can you please try the new version before I update the expansion in the eCloud?
You can download it from [here](https://aboodyy.net/expansions/Progress-Expansion-1.8.jar).
To install it in your server, simply replace the old jar with the new one in the `plugins/PlaceholderAPI/expansions` folder.

Let me know how it goes for you,

Thank you,
aBooDyy

**Comment by Darwin1546** [comment]
Can you upload that update please?

**Comment by aBooDyy** [comment]
Hello there,

I've totally forgotten about this 😅 
From your message, seems like it is working fine.
[Updated](https://api.extendedclip.com/expansions/progress/versions/progress-18/).

Have a nice day,
aBooDyy
