### ISSUE TITLE
Bungee with Bar

### ISSUE THREAD

**Issue by Tomigames** [aBooDyy/Progress-Expansion#6]
Hi I am trying to do a bar for the status of a server in the bungee network. I am sure this is really easy but I can't seem to figure it out. 
%progress_bar_%bungee_Survival%_c:&c■_p:&6■_r:&7■_l:5_m:60_fullbar:&cFull!%

**Comment by aBooDyy** [comment]
Hello there,

All placeholders used inside of the progress placeholder should be added using curly braces `{}` and not percentage signs `%%`.
Take a look at the README.md file for more work info.

Let me know if that fixes it.

Kind regards,
aBooDyy

**Comment by Tomigames** [comment]
Thank you much apreciated.
