### ISSUE TITLE
Broken latest Placeholder API

### ISSUE THREAD

**Issue by Jhezreel708** [aBooDyy/Progress-Expansion#7]
this extension is broken upon updating to the latest version of PLACEHODLERAPI 
PLACEHOLDERAPI-2.10.8

**Comment by aBooDyy** [comment]
Hello there,

Thanks for reaching out!
It's probably due to the API changes in the latest update of PlaceholderAPI.
Unfortunately, I haven't had the time to update the expansion yet. Will try to update it tomorrow.

Will let you know when I do :)
aBooDyy

**Comment by aBooDyy** [comment]
It has been updated by Clip in the cloud with the fix made in #8.
Just download the expansion again to update it.

Regards,
aBooDyy

**Comment by Jhezreel708** [comment]
Thank you! Good luck :)
